# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use Vagrant's default insecure key
  config.ssh.insert_key = false
  # Set timeout to 3 mins
  config.vm.boot_timeout = 180
  # Disable default host <-> guest synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # Disable fstab modification
  config.vm.allow_fstab_modification = false
  # Disable hosts modification
  config.vm.allow_hosts_modification = false
  # Set guest OS type to disable autodetection
  config.vm.guest = :freebsd

  config.vm.provider :libvirt do |domain|
    domain.cpus = 1
    domain.memory = 1024 
    domain.disk_driver :cache => 'none'
    domain.graphics_type = 'none'
  end
end
